sever:
  port: 8080

spring:
  datasource:
#    url: jdbc:mysql://47.102.109.90:3306/shopping_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.102.109.90:3306/shopping_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml


