sever:
  port: 8081

spring:
  datasource:
#    url: jdbc:mysql://47.102.109.90:3306/shopping_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
    url: jdbc:mysql://47.102.109.90:3306/shopping_mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

#cms_*：内容管理模块相关表
#oms_*：订单管理模块相关表
#pms_*：商品模块相关表
#sms_*：营销模块相关表
#ums_*：会员模块相关表
